### ISSUE TITLE
Accessing global variables from within the fast_map function

### ISSUE THREAD

**Issue by mvolar** [michalmonday/fast_map#2]
Hello,

I love the idea of the package, however I was wondering is there any way to pass immutable global variables into the function body using fast_map()? Normal python map() supports this, so by running this:

```
from fast_map import fast_map
import time

def task_with_multiple_params(a, b):
    return a + b + c

if __name__ == '__main__':
    c=5
    print(c)
    print('Using function with multiple parameters:')
    for s in map(task_with_multiple_params, [1,2,3], [1,2,3]):
        print(s)
    
```
the output is `7
9
11`

But when I run the same code using fast_map() instead of map() I get the following error:
`NameError: name 'c' is not defined`

I understand this could be a problem of the multiprocessing library which doesn't allow mutable global variables to be used in functions when multithreaded so I was wondering if a workaround for this library was possible.  Python map() function gets around this by allowing global variables since everything gets done on a single thread so there are no simultaneous READ/WRITE operations at the same variable memory adress.

Additional reason for posing this question is that for example in my code unfortunately using multiple parameters with same data copied over the length of the list is hard to implement since there are multiple large global matrices, so creating a list of 32000 elements of the same 50000x50000 matrix (to make it iterable) is very memory intensive, and the matrices are not changed as a result of the function. So for example this works normally:

```
from fast_map import fast_map
import time

def task_with_multiple_params(a, b, c):
    return a + b + c

if __name__ == '__main__':
    c=[5,5,5]
    print(c)
    print('Using function with multiple parameters:')
    for s in fast_map(task_with_multiple_params, [1,2,3], [1,2,3],c):
        print(s)
    
```
But isn't feasible.

Thanks in advance,

**Comment by michalmonday** [comment]
Hello, sorry for late response, I tried to reproduce the error but running the code below with `fast_map` instead of `map` worked well for me and the `NameError` didn't occur:
```python
from fast_map import fast_map
import time

def task_with_multiple_params(a, b):
    return a + b + c

if __name__ == '__main__':
    c=5
    print(c)
    print('Using function with multiple parameters:')
    for s in map(task_with_multiple_params, [1,2,3], [1,2,3]):
        print(s)    
```

I used python 3.7.15 on Lubuntu 18.04 with 0.0.8 version of fast_map.
