### ISSUE TITLE
0.1.1 / 0.2.0 release timeline?

### ISSUE THREAD

**Issue by Roach** [michalmonday/fast_map#6]
Hey Michael, 

Thanks for your hard work on this library. It definitely makes threading/mutiproc simpler.

Can I get a timeline on releasing the recent changes to PyPi? 🙇🏻‍♂️

**Comment by michalmonday** [comment]
Hello, uploaded 0.2.0 now, thank you for the update with terminating spawned processes.

**Comment by Roach** [comment]
Awesome! Thank you 🙏
